name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-test:
    name: Perform unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: unit_test_report
          path: app/build/reports/test/testDebugUnitTest/

  instrumented-test:
    name: Perform Instrumentation Testing
    needs: [unit-test]
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Java JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 36
          script: ./gradlew connectedAndroidTest

      - name: Upload Instrumentation Test report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected
